const canvas = document.getElementById('court');
const ctx = canvas.getContext('2d');
const playerScoreEl = document.getElementById('playerScore');
const opponentScoreEl = document.getElementById('opponentScore');
const rallyEl = document.getElementById('rallyLabel');
const roundEl = document.getElementById('roundNumber');
const statusEl = document.getElementById('gameStatus');
const energyBar = document.getElementById('energyBar');
const toast = document.getElementById('serveToast');
const hint = document.getElementById('courtHint');
let W=900,H=510,dpr=1,keys={},last=0,raf;
let state={player:0,opponent:0,rally:0,round:1,playing:false,over:false,serveTimer:0,playerX:.22,aiX:.78,hitFlash:0,energy:32,kit:'#c4f0d4',shuttle:{x:.35,y:.54,vx:.17,vy:-.62,side:'ai'},trail:[],particles:[],swing:0,aiSwing:0};
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(2,window.devicePixelRatio||1);W=r.width;H=r.height;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
window.addEventListener('resize',resize); resize();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const lerp=(a,b,t)=>a+(b-a)*t;
function resetGame(){state={...state,player:0,opponent:0,rally:0,round:1,playing:false,over:false,serveTimer:0,playerX:.22,aiX:.78,hitFlash:0,energy:32,shuttle:{x:.35,y:.54,vx:.17,vy:-.62,side:'ai'},trail:[],particles:[],swing:0,aiSwing:0}; updateHud(); showToast('准备发球'); draw()}
function startGame(){if(state.over) resetGame(); state.playing=true; state.serveTimer=1.1; statusEl.textContent='比赛进行中'; hint.style.opacity='.92'; showToast('你的发球'); updateHud()}
function showToast(t){toast.textContent=t;toast.classList.remove('show');void toast.offsetWidth;toast.classList.add('show')}
function updateHud(){playerScoreEl.textContent=String(state.player).padStart(2,'0');opponentScoreEl.textContent=String(state.opponent).padStart(2,'0');roundEl.textContent=String(state.round).padStart(2,'0');rallyEl.textContent=state.over?(state.player>state.opponent?'YOU WIN':'NEXT ROUND'):state.playing?(state.rally?`RALLY ${String(state.rally).padStart(2,'0')}`:'READY?'):'READY?';energyBar.style.width=`${state.energy}%`}
function score(who){if(who==='player')state.player++;else state.opponent++;state.round++;state.rally=0;state.energy=32;state.shuttle={x:who==='player'?.72:.28,y:.53,vx:who==='player'?.18:-.18,vy:-.56,side:who==='player'?'player':'ai'};showToast(who==='player'?'POINT!':'OPPONENT POINT');if(state.player>=21||state.opponent>=21){state.over=true;state.playing=false;statusEl.textContent=state.player>state.opponent?'你赢了！':'再来一局';hint.style.opacity='.5'}updateHud()}
function particle(x,y,color){state.particles.push({x,y,vx:(Math.random()-.5)*.35,vy:(Math.random()-.7)*.35,a:1,c:color})}
function swing(){if(!state.playing||state.over||state.serveTimer>0)return;state.swing=.22;const s=state.shuttle;if(s.side==='ai'&&s.x<.5&&Math.abs(s.x-state.playerX)<.18&&s.y>.28&&s.y<.72){const quality=1-Math.abs(s.x-state.playerX)/.18; s.side='player';s.vx=.34+.18*quality;s.vy=-(.55+.3*quality);state.rally++;state.energy=clamp(state.energy+13,0,100);for(let i=0;i<5;i++)particle(s.x*W,groundY(s.y),state.kit);showToast(quality>.72?'PERFECT!':'NICE HIT');updateHud()} }
function update(dt){if(!state.playing)return;if(state.serveTimer>0){state.serveTimer-=dt;if(state.serveTimer<=0){state.shuttle={x:.34,y:.53,vx:.18,vy:-.64,side:'ai'};showToast('回球！')}return}state.swing=Math.max(0,state.swing-dt);state.aiSwing=Math.max(0,state.aiSwing-dt);const p=state.playerX+(keys.ArrowRight||keys.d?dt*.7:0)-(keys.ArrowLeft||keys.a?dt*.7:0);state.playerX=clamp(p,.08,.43);const target=state.shuttle.side==='ai'?state.shuttle.x:.78;state.aiX=lerp(state.aiX,clamp(target,.58,.92),dt*2.7);const s=state.shuttle;s.vy+=1.1*dt;s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.x<.5&&s.side==='ai'&&s.y<.56&&s.vy>0){/* waiting for hit */}if(s.side==='player'&&s.x>.63&&s.y<.58&&state.aiSwing<=0){state.aiSwing=.25;s.side='ai';s.vx=-(.29+Math.random()*.14);s.vy=-(.55+Math.random()*.3);state.rally++;state.energy=clamp(state.energy+8,0,100);updateHud()}if(s.y>.82){score(s.x<.5?'opponent':'player')}if(s.x<.04||s.x>.96){score(s.x<.5?'opponent':'player')}state.trail.push({x:s.x,y:s.y});if(state.trail.length>9)state.trail.shift();state.particles.forEach(q=>{q.x+=q.vx*dt*60;q.y+=q.vy*dt*60;q.vy+=.015;q.a-=dt*1.6});state.particles=state.particles.filter(q=>q.a>0);state.hitFlash=Math.max(0,state.hitFlash-dt)}
function groundY(y){return H*.69+y*H*.22}
function court(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#b8d8ca');g.addColorStop(.57,'#d4e3d0');g.addColorStop(.575,'#d39863');g.addColorStop(1,'#b9754e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.26)';for(let i=0;i<7;i++)ctx.fillRect(0,H*.6+i*17,W,1);ctx.fillStyle='rgba(17,67,66,.08)';ctx.beginPath();ctx.arc(W*.12,H*.12,90,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(247,229,167,.5)';ctx.beginPath();ctx.arc(W*.88,H*.12,70,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(22,72,68,.52)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(W*.04,H*.71);ctx.lineTo(W*.96,H*.71);ctx.moveTo(W*.5,H*.64);ctx.lineTo(W*.5,H*.91);ctx.stroke();ctx.strokeStyle='rgba(255,245,213,.56)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(W*.07,H*.68);ctx.lineTo(W*.93,H*.68);ctx.stroke();for(let i=0;i<8;i++){ctx.fillStyle=`rgba(255,255,255,${.08+i*.01})`;ctx.fillRect(0,H*.64+i*22,W,1)}}
function net(){const x=W*.5,y=H*.59,h=H*.24;ctx.strokeStyle='#277174';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y-h);ctx.lineTo(x,y+h);ctx.stroke();ctx.beginPath();ctx.moveTo(x+6,y-h+8);ctx.lineTo(x+6,y+h-8);ctx.stroke();ctx.strokeStyle='rgba(250,249,230,.8)';ctx.lineWidth=1;for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(x+7,y-h+10+i*15);ctx.lineTo(x+7,y+h-8);ctx.stroke()}ctx.beginPath();ctx.moveTo(x,y-h);ctx.lineTo(x+8,y-h+10);ctx.stroke()}
function drawPlayer(x,side,kit,opponent=false,swinging=false){const px=x*W,base=H*.72,scale=Math.min(W/900,1.15),mirror=side==='right'?-1:1;ctx.save();ctx.translate(px,base);ctx.scale(mirror*scale,scale);ctx.fillStyle='rgba(20,50,50,.18)';ctx.filter='blur(7px)';ctx.beginPath();ctx.ellipse(0,5,48,9,0,0,Math.PI*2);ctx.fill();ctx.filter='none';ctx.strokeStyle='#24484a';ctx.lineCap='round';ctx.lineWidth=13;ctx.beginPath();ctx.moveTo(-10,-12);ctx.lineTo(-27,52);ctx.moveTo(8,-12);ctx.lineTo(33,51);ctx.stroke();ctx.fillStyle=opponent?'#e88672':kit;ctx.beginPath();ctx.moveTo(-35,-132);ctx.quadraticCurveTo(-41,-67,-25,-10);ctx.quadraticCurveTo(3,4,30,-10);ctx.quadraticCurveTo(44,-65,30,-126);ctx.quadraticCurveTo(0,-151,-35,-132);ctx.fill();ctx.fillStyle='rgba(0,0,0,.12)';ctx.beginPath();ctx.ellipse(16,-63,9,47,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#be6b4b';ctx.beginPath();ctx.arc(0,-164,32,0,Math.PI*2);ctx.fill();ctx.fillStyle='#20393b';ctx.beginPath();ctx.arc(-4,-180,31,Math.PI*1.04,Math.PI*2.05);ctx.quadraticCurveTo(14,-186,28,-168);ctx.lineTo(21,-145);ctx.quadraticCurveTo(4,-156,-3,-160);ctx.fill();ctx.fillStyle='#20393b';ctx.beginPath();ctx.arc(-24,-167,8,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b96243';ctx.lineWidth=13;ctx.beginPath();ctx.moveTo(-24,-118);ctx.lineTo(swinging?55:-57,-79);ctx.stroke();ctx.beginPath();ctx.moveTo(23,-118);ctx.lineTo(swinging?65:56,-48);ctx.stroke();ctx.strokeStyle='#375957';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(swinging?65:56,-48,swinging?65:56,-48);ctx.lineTo(swinging?88:78,-18);ctx.stroke();ctx.strokeStyle='#456866';ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(swinging?96:85,-5,25,35,.5,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.68)';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(swinging?96:85,-5,19,29,.5,0,Math.PI*2);ctx.stroke();ctx.fillStyle=opponent?'#e67859':'#eb7759';ctx.beginPath();ctx.ellipse(-32,56,29,11,-.1,0,Math.PI*2);ctx.ellipse(32,56,29,11,.1,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawShuttle(){const s=state.shuttle;state.trail.forEach((p,i)=>{ctx.fillStyle=`rgba(248,249,222,${i/state.trail.length*.18})`;ctx.beginPath();ctx.arc(p.x*W,groundY(p.y),2+i*.2,0,Math.PI*2);ctx.fill()});const x=s.x*W,y=groundY(s.y);ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(s.vy,s.vx)-Math.PI/2);ctx.fillStyle='#f6f6da';ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(-10,10);ctx.lineTo(10,10);ctx.closePath();ctx.fill();ctx.strokeStyle='#d4b974';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#fffdf0';ctx.beginPath();ctx.arc(0,11,5,0,Math.PI*2);ctx.fill();ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);court();net();drawPlayer(state.playerX,'left',state.kit,false,state.swing>0);drawPlayer(state.aiX,'right','#f0b17e',true,state.aiSwing>0);drawShuttle();state.particles.forEach(q=>{ctx.globalAlpha=q.a;ctx.fillStyle=q.c;ctx.beginPath();ctx.arc(q.x,q.y,3,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;if(state.hitFlash>0){ctx.fillStyle=`rgba(255,255,220,${state.hitFlash*.3})`;ctx.fillRect(0,0,W,H)}}
function loop(t){const dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);draw();raf=requestAnimationFrame(loop)}
window.addEventListener('keydown',e=>{keys[e.key]=true;if(e.code==='Space'){e.preventDefault();swing()}if(e.key==='Enter'&&!state.playing)startGame()});window.addEventListener('keyup',e=>keys[e.key]=false);
document.getElementById('playBtn').addEventListener('click',()=>{document.getElementById('game').scrollIntoView({behavior:'smooth'});startGame()});document.getElementById('restartBtn').addEventListener('click',resetGame);document.querySelectorAll('.swatch').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.kit=b.dataset.color}));document.querySelectorAll('.locked').forEach(b=>b.addEventListener('click',()=>showToast('即将开放')));document.getElementById('soundBtn').addEventListener('click',e=>{e.currentTarget.textContent=e.currentTarget.textContent==='◖)))'?'◖··':'◖)))'});resetGame();raf=requestAnimationFrame(loop);
